#! /bin/sh


aclocal
autoconf
automake --add-missing
./configure
make

rm -f *.o
rm -f Makefile.in
rm -f configure
rm -rf aclocal.m4
rm -rf autom4te.cache
rm -f config.log
rm -f config.status
rm -f core.*
rm -f depcomp
rm -f install-sh
rm -f Makefile
rm -f missing
